# Generated by Django 2.1.15 on 2021-07-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0012_auto_20210701_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(auto_now=True, null=True)),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_by', to='assets.Staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Staff')),
            ],
        ),
    ]
