# Generated by Django 2.1.15 on 2021-07-08 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_trans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
