# Generated by Django 2.1.15 on 2021-06-21 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20210621_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='toLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toLocation', to='assets.Location'),
        ),
    ]
