# Generated by Django 2.1.15 on 2021-06-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20210621_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='toLocation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
