# Generated by Django 2.1.15 on 2021-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20210621_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='toLocation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
