# Generated by Django 2.1.15 on 2021-06-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20210621_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amodel',
            name='make',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='amodel',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='make',
        ),
        migrations.DeleteModel(
            name='Amodel',
        ),
        migrations.DeleteModel(
            name='Make',
        ),
    ]
