# Generated by Django 2.1.15 on 2021-06-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20210630_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='lpoNumber',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='price',
        ),
    ]
