# Generated by Django 3.0.5 on 2020-04-23 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0002_auto_20200423_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toners',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 12, 6, 35, 911516)),
        ),
    ]
