# Generated by Django 3.0.5 on 2020-04-26 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0003_auto_20200423_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='tonermodels',
            options={'verbose_name_plural': 'Tonermodels'},
        ),
        migrations.AlterModelOptions(
            name='toners',
            options={'verbose_name_plural': 'Toners'},
        ),
        migrations.AlterField(
            model_name='toners',
            name='created_on',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 26, 12, 15, 26, 325809, tzinfo=utc)),
        ),
    ]
