# Generated by Django 3.0.5 on 2020-04-26 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0004_auto_20200426_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toners',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 12, 16, 46, 457372, tzinfo=utc)),
        ),
    ]
