# Generated by Django 2.1.15 on 2021-09-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toLocation', to='assets.Vendor'),
        ),
    ]
