# Generated by Django 2.1.15 on 2021-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_delivery_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
