# Generated by Django 3.0.6 on 2020-08-30 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
